spring.application.name=teacher
spring.datasource.url=jdbc:mysql://localhost:3306/sprk_microservice_student_file_upload_teacher?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=123456
spring.jpa.hibernate.ddl-auto=update

server.port=8081
spring.jpa.show.sql=true

spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.orm.jdbc.bind=TRACE


file.upload-dir=D:/Software Development/Spring/Spring Boot/student/uploads
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

spring.secret=c3Bya19zcHJpbmdfc2VjdXJpdHlfc2VjcmV0X2NvZGVfMTI=