spring.application.name=spring_openai

#spring.ai.model.chat=openai-sdk
spring.ai.openai.api-key=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
spring.ai.openai.chat.options.model=gpt-4o-mini