services:
  mysql:
    image: mysql:8.0
    container_name: olderSQL
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: sprk_demo
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
  newsqlproject:
    build: .
    container_name: newsqlproject-container
    ports:
      - "8084:8080"
    depends_on:
      - mysql
volumes:
  mysql-data: