#spring.application.name=spring_ai_project
#
#spring.ai.model.chat=openai-sdk
#spring.ai.openai.api-key=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
#spring.ai.openai.chat.options.model=gpt-4o-mini


spring.application.name=spring_ai_project

spring.ai.model.chat=ollama
spring.ai.ollama.chat.options.model=llama3
spring.ai.ollama.base-url=http://localhost:11434
