spring.application.name=api_Gateway
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
server.port=8082
spring.cloud.gateway.server.webflux.routes[0].id=student
spring.cloud.gateway.server.webflux.routes[0].uri=lb://student
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/v1/student/**

spring.cloud.gateway.server.webflux.routes[1].id=teacher
spring.cloud.gateway.server.webflux.routes[1].uri=lb://teacher
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/v1/teacher/**
